### PR TITLE
Responsive theme

### LINKED ISSUE #12: Make AskTheEU theme responsive, and up to date with latest core improvements
Will look something like this, except with more impactful headings, CTAs, and top requests on the homepage:

homepage

request page

content page

### PR DESCRIPTION
**Pull request by zarino**
Fixes #12.

Not quite done yet. Things that need fixing:

- [x] Sort out nav bar links
- [x] <del>Check Andreas is happy with the prominence of the "Send a request" button on the homepage (I have a feeling he won't be)</del> – He hasn't mentioned it as a problem, so I think we're good!
- [x] Merge back in all the custom about / help pages from the current site (although, from the look of the mockup, we were perhaps going to simplify them too, because they're quite dense right now!)
- [x] Some minor styling changes for the about / help pages once that's done
- [x] "Find out more" doesn't link anywhere on homepage hero
- [x] Footer is missing a lot of the original stuff (see https://github.com/mysociety/asktheeu-theme/pull/13#issuecomment-163988362)
- [x] Squash
- [x] Create and shorten nav translations

Here's how it looks right now:

screen shot 2015-11-18 at 15 42 19
screen shot 2015-11-18 at 15 42 23
screen shot 2015-11-18 at 15 43 02

### CODE REVIEW

**Comment by wrightmartin** [comment]
[ ] Note for me to do @wrightmartin

**Comment by zarino** [comment]
@crowbot – user menu links now fixed on mobile and desktop

screen shot 2015-12-10 at 16 58 42

**Comment by garethrees** [comment]
Could a designer (or someone with photoshop installed) cut out https://github.com/mysociety/asktheeu-theme/blob/master/assets/images/widget-base.png to look like this (note the transparent bg)?

widget-base

**Comment by garethrees** [comment]
Footer is missing a lot of the original stuff (address, phone numbers and the "Other original content was developed by Access Info Europe and is made public under a Creative Commons Attribution, Share Alike licence." sentence)

**Comment by garethrees** [comment]
Blog page needs some work if they want to retain the original design

**Comment by garethrees** [comment]
Not sure where "Find out more" is supposed to link to in the frontpage hero

**Comment by andreaspavlou** [comment]
Hi guys, I dont want to be a pain by adding things to do, as you have done a great job so far! 

However, with the main menu bar items, could we have the following (in this order) ... 
How it works - /en/help/about
Which EU body? - /en/body/list/all
Make a Request - /select_authority
Browse all Requests - /en/list/all
News & Campaigns - en/blog
Search bar

It all fitted on one line when I tried with 'inspect element' - fingers crossed the same when done properly :)

Also, the 'find out more' link on the front page should lead to /en/help/about 

Other than that I have no other comments :) We will maybe tomorrow try to do a pull request for our updated about/help pages..

Thanks!

**Comment by garethrees** [comment]
> It all fitted on one line when I tried with 'inspect element' - fingers crossed the same when done properly :)

I had to shorten some of the names so that it doesn't break at smaller screen sizes before the break point. Setting the locale to [French](http://staging.alaveteli.org/fr) breaks the layout due to the longer phrases.

**Comment by zarino** [comment]
Looking at French specifically, we currently have "Demander l'access à une information" as a translation for "Make a request". I wonder whether we could translate it instead to "Faire un demande"? Seems ridiculous to be massaging link text to fit into a space, but we do it in English sometimes, so why not here ;-)

I'll also add a commit that makes the search box a bit narrower, just because it's pretty uncontentious and will help in cases where we're *ever so slightly* too wide.

**Comment by garethrees** [comment]
Good to merge:

- rebase
- make new ticket for nav translations

**Comment by garethrees** [comment]
Just waiting on extra translations

**Comment by andreaspavlou** [comment]
The French and Spanish translations  are all done. German will be done after the upgrade as we do not have a translator right now.

**Comment by andreaspavlou** [comment]
Sorry to be a pian, but I notice there is no link to the AsktheEU.org twitter account on the front page ... would it be possible to include somewhere? http://www.twitter.com/AsktheEU

**Comment by garethrees** [comment]
> The French and Spanish translations are all done. German will be done after the upgrade as we do not have a translator right now.

Updated

> Sorry to be a pian, but I notice there is no link to the AsktheEU.org twitter account on the front page ... would it be possible to include somewhere? http://www.twitter.com/AsktheEU

No problem, done!

**Pull request merged**
